# golangci-lint configuration v2 format for golangci-lint-action@v8
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  go: '1.22'

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    enable:
      - asmdecl
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - directive
      - errorsas
      - framepointer
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - sigchanyzer
      - slog
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - timeformat
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - fieldalignment
      - shadow
  
  gocyclo:
    min-complexity: 80
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 2
    min-occurrences: 3
  
  misspell:
    locale: US
    ignore-words:
      - cancelled
  
  lll:
    line-length: 140
    tab-width: 1
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  funlen:
    lines: 250
    statements: 160
    ignore-comments: true
  
  gosec:
    excludes:
      - G115  # Integer overflow conversion
  
  staticcheck:
    checks:
      - all

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional linters
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - nolintlint
    - unconvert
    - unparam
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - gocyclo
    
    # Exclude long lines for go:generate statements
    - linters:
        - lll
      source: "^//go:generate "
    
    # Exclude all linters for generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    
    # Exclude all linters for vendor and testdata
    - path: "(vendor|testdata)/"
      linters:
        - all

output:
  formats:
    colored-line-number:
      path: stdout
